[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "bash start.sh"
