[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "superset run -h 0.0.0.0 -p $PORT --with-threads --reload"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10